project:
  type: book

book:
  title: "Test ILM"
  author: "Test Author"
  date: "2024-01-01"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
  appendices:
    - appendix.qmd
    - appendix-b.qmd

bibliography: references.bib

crossref:
  custom:
    - kind: float
      key: dino
      reference-prefix: Dinosaur

format:
  ilm-typst:
    keep-typ: true
